export const LOCALE_SET = 'LOCALE_SET';
export const SHOW_PRİCE_TYPE_SET = 'SHOW_PRİCE_TYPE_SET';


export const SET_EXCHANGE = 'SET_EXCHANGE';

export const HEADER_INPUT_REQUEST = 'HEADER_INPUT_REQUEST';
export const HEADER_INPUT_SUCCESS = 'HEADER_INPUT_SUCCESS';
export const HEADER_INPUT_FAILURE = 'HEADER_INPUT_FAILURE';
export const HEADER_INPUT_EXCHANGE = 'HEADER_INPUT_EXCHANGE';
export const HEADER_INPUT_PROCESS = 'HEADER_INPUT_PROCESS';
export const HEADER_INPUT_ADD = 'HEADER_INPUT_ADD';
export const HEADER_INPUT_REMOVE = 'HEADER_INPUT_REMOVE';
export const HEADER_INPUT_LANG = 'HEADER_INPUT_LANG';
export const HEADER_INPUT_PERCENT = 'HEADER_INPUT_PERCENT';

export const HEADER_OUTPUT_REQUEST = 'HEADER_OUTPUT_REQUEST';
export const HEADER_OUTPUT_SUCCESS = 'HEADER_OUTPUT_SUCCESS';
export const HEADER_OUTPUT_FAILURE = 'HEADER_OUTPUT_FAILURE';
export const HEADER_OUTPUT_EXCHANGE = 'HEADER_OUTPUT_EXCHANGE';
export const HEADER_OUTPUT_PROCESS = 'HEADER_OUTPUT_PROCESS';
export const HEADER_OUTPUT_ADD = 'HEADER_OUTPUT_ADD';
export const HEADER_OUTPUT_REMOVE = 'HEADER_OUTPUT_REMOVE';
export const HEADER_OUTPUT_LANG = 'HEADER_OUTPUT_LANG';
export const HEADER_OUTPUT_PERCENT = 'HEADER_OUTPUT_PERCENT';





export const HEADER_MAIN_TOTALS_REQUEST = 'HEADER_MAIN_TOTALS_REQUEST';
export const HEADER_MAIN_TOTALS_SUCCESS = 'HEADER_MAIN_TOTALS_SUCCESS';
export const HEADER_MAIN_TOTALS_FAILURE = 'HEADER_MAIN_TOTALS_FAILURE';


export const MAIN_HEADER_REQUEST = 'MAIN_HEADER_REQUEST';
export const MAIN_HEADER_SUCCESS = 'MAIN_HEADER_SUCCESS';
export const MAIN_HEADER_FAILURE = 'MAIN_HEADER_FAILURE';


export const GET_DETAIL_REQUEST = 'GET_DETAIL_REQUEST';
export const GET_DETAIL_SUCCESS = 'GET_DETAIL_SUCCESS';
export const GET_DETAIL_FAILURE = 'GET_DETAIL_FAILURE';

export const GET_ITEMS_REQUEST = 'GET_ITEMS_REQUEST';
export const GET_ITEMS_SUCCESS = 'GET_ITEMS_SUCCESS';
export const GET_ITEMS_FAILURE = 'GET_ITEMS_FAILURE';


export const SAVE_TITLE_REQUEST = 'SAVE_TITLE_REQUEST';
export const SAVE_TITLE_SUCCESS = 'SAVE_TITLE_SUCCESS';
export const SAVE_TITLE_FAILURE = 'SAVE_TITLE_FAILURE';


export const SAVE_ITEM_REQUEST = 'SAVE_ITEM_REQUEST';
export const SAVE_ITEM_SUCCESS = 'SAVE_ITEM_SUCCESS';
export const SAVE_ITEM_FAILURE = 'SAVE_ITEM_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const SET_USER_DATA = 'SET_USER_DATA';


export const EXCHANGE_REQUEST = 'EXCHANGE_REQUEST';
export const EXCHANGE_SUCCESS = 'EXCHANGE_SUCCESS';
export const EXCHANGE_FAILURE = 'EXCHANGE_FAILURE';



export const GET_ITEM_OF_HEADERS_REQUEST = 'GET_ITEM_OF_HEADERS_REQUEST';
export const GET_ITEM_OF_HEADERS_SUCCESS = 'GET_ITEM_OF_HEADERS_SUCCESS';
export const GET_ITEM_OF_HEADERS_FAILURE = 'GET_ITEM_OF_HEADERS_FAILURE';

export const GET_ALL_ITEM_OF_HEADERS_REQUEST = 'GET_ALL_ITEM_OF_HEADERS_REQUEST';
export const GET_ALL_ITEM_OF_HEADERS_SUCCESS = 'GET_ALL_ITEM_OF_HEADERS_SUCCESS';
export const GET_ALL_ITEM_OF_HEADERS_REMOVE = 'GET_ALL_ITEM_OF_HEADERS_REMOVE';
export const GET_ALL_ITEM_OF_HEADERS_FAILURE = 'GET_ALL_ITEM_OF_HEADERS_FAILURE';

export const GET_ITEM_FROM_DATE_REQUEST = 'GET_ITEM_FROM_DATE_REQUEST';
export const GET_ITEM_FROM_DATE_SUCCESS = 'GET_ITEM_FROM_DATE_SUCCESS';
export const GET_ITEM_FROM_DATE_FAILURE = 'GET_ITEM_FROM_DATE_FAILURE';
export const GET_ITEM_FROM_DATE_CLEAR = 'GET_ITEM_FROM_DATE_CLEAR';


export const DELETE_ITEMS_REQUEST = 'DELETE_ITEMS_REQUEST';
export const DELETE_ITEMS_SUCCESS = 'DELETE_ITEMS_SUCCESS';
export const DELETE_ITEMS_FAILURE = 'DELETE_ITEMS_FAILURE';
