export const LOCALE_SET = 'LOCALE_SET';


export const HEADER_INPUT_REQUEST = 'HEADER_INPUT_REQUEST';
export const HEADER_INPUT_SUCCESS = 'HEADER_INPUT_SUCCESS';
export const HEADER_INPUT_FAILURE = 'HEADER_INPUT_FAILURE';


export const HEADER_OUTPUT_REQUEST = 'HEADER_OUTPUT_REQUEST';
export const HEADER_OUTPUT_SUCCESS = 'HEADER_OUTPUT_SUCCESS';
export const HEADER_OUTPUT_FAILURE = 'HEADER_OUTPUT_FAILURE';


export const GET_DETAIL_REQUEST = 'GET_DETAIL_REQUEST';
export const GET_DETAIL_SUCCESS = 'GET_DETAIL_SUCCESS';
export const GET_DETAIL_FAILURE = 'GET_DETAIL_FAILURE';


export const SAVE_TITLE_REQUEST = 'SAVE_TITLE_REQUEST';
export const SAVE_TITLE_SUCCESS = 'SAVE_TITLE_SUCCESS';
export const SAVE_TITLE_FAILURE = 'SAVE_TITLE_FAILURE';
